### ISSUE TITLE
OUU: Problem with constraint

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#110]
I tried to run OUU, where I have a constraint.

- To do this, I made up a constraint variable in the Flowsheet, where the value of the variable has to be negative.
- In the OUU tab, under "Outputs", I specified the constraint variable as "Inequality Constraint".
- Shortly after clicking "Run OUU", I received the following error message:

<img width="263" alt="ouu_02_26_2018" src="https://user-images.githubusercontent.com/30811140/36688935-e0ce93a6-1b25-11e8-913e-a7f991d39cf4.png">

**Comment by fsoepyan** [comment]
- I tried running OUU with an inequality constraint using PSUADE 1.7.12
- I still got the same error message from my first comment
- The "Stop" button did not return to the "Run OUU" button
- Therefore, I'm reopening Issue #101

**Comment by sotorrio1** [comment]
Two separate issues here. It's true the new psuade version should be able to handle constraints and it's not. We'll double check with Charles if there is anything wrong with the driver and the commands sent to psuade. The stop button works, but when there is another error the communication with psuade stops and it's not getting any other messages/instructions. That's why it seems the stop button doesn't work

**Comment by ksbeattie** [comment]
@sotorrio1 will follow up with Charles Tong on this.

**Comment by sotorrio1** [comment]
Should be fixed with PR #270 
@fsoepyan would you mind checking if it now works for you? Thanks!

**Comment by fsoepyan** [comment]
- I downloaded FOQUS from "sotorrio1-patch-1" (PR #270)
- I tested the OUU tab using an example problem, where I have 3 constraints
- For each constraint, the variables C01 to C03 must be negative
- After clicking "Run OUU", I still get the same error message that I got in my original comment

**Comment by sotorrio1** [comment]
@fsoepyan Are you running the example you sent me a while ago "MEA_Column_02_23_2018.foqus" ?
The one with 17 inputs (X1-X4 are Z1 and the rest Z4), surrogate.negCO2 as the objective and C01, C02 and C03 as inequality constraints. I tried running that one and the issue I'm getting is that even if I tell OUU to generate the samples for Z4, it crashes because I didn't provide a sample file... 

Do you get the same issue? Please send me the psuadelog.

Thanks!

**Comment by fsoepyan** [comment]
@sotorrio1: Yes, I did run the OUU tab using the file that you mentioned, with the 17 variables, the negCO2 objective, and the 3 inequality constraints.

Below is the psuadelog:

**********************************************************************
*      Welcome to PSUADE (version 1.7.12)
**********************************************************************
PSUADE - A Problem Solving environment for 
         Uncertainty Analysis and Design Exploration (1.7.12)
(for help, enter <help>)
======================================================================
psuade> **********************************************************************
PSUADE : Search for local minima in sample space.
         number of samples = 1
	 optimization starting point 1 : 
		  3.84400000e+003
		 -7.74900000e+003
		  3.92000000e+000
		  1.75000000e+000
		 -1.34200000e+003
		  1.39000000e+000
		  0.00000000e+000
		  1.22000000e+001
		  5.58000000e-001
		  1.12400000e+003
		  1.60000000e-001
		  2.94000000e-001
		 -1.90490000e+008
		 -4.91270000e+008
		 -3.24303000e+008
		 -6.96303000e+008
		  2.89000000e+001
				 Y =  1.00000000e+035
**********************************************************************
**********************************************************************
PSUADE OPTIMIZATION 1 (1) : 
	 starting X(     1) =  3.84400000e+003
	 starting X(     2) = -7.74900000e+003
	 starting X(     3) =  3.92000000e+000
	 starting X(     4) =  1.75000000e+000
	 starting X(     5) = -1.34200000e+003
	 starting X(     6) =  1.39000000e+000
	 starting X(     7) =  0.00000000e+000
	 starting X(     8) =  1.22000000e+001
	 starting X(     9) =  5.58000000e-001
	 starting X(    10) =  1.12400000e+003
	 starting X(    11) =  1.60000000e-001
	 starting X(    12) =  2.94000000e-001
	 starting X(    13) = -1.90490000e+008
	 starting X(    14) = -4.91270000e+008
	 starting X(    15) = -3.24303000e+008
	 starting X(    16) = -6.96303000e+008
	 starting X(    17) =  2.89000000e+001
	 starting Y =  1.00000000e+035
**********************************************************************
**********************************************************************
*     1- OR 2-STAGE OPTIMIZATION UNDER UNCERTAINTY (OUU)
======================================================================
This optimization capability solves the following problem:

   minimize_Z1 { Phi_{Z3,Z4} [ G(Z1,Z2,Z3,Z4) ] } 

   subject to either:
    (a) bound constraints on Z1, Z2, and Z4 (use bobyqa); or 
    (b) no constraint on Z1, Z2, and Z4 (use newuoa); or
    (c) inequality constraints on Z1,Z2,Z3,Z4 (use cobyla)
    as the level-1 optimizer.)

   Z3 is a set of discrete parameters for which a sample

   is to be provided by the user. 

   (0) How to perform regular optimization? 
       In this case 
       - Z1 will be the optimization variables
       - Z2 should be an empty set
       - Z3 should be an empty set
       - Z4 should be an empty set
       - G(Z1,Z3,Z4)=G(Z1) is the simulator (opt_driver)
   (1) How to perform 1-level OUU? 
       In this case 
       - Z1: the optimization variables
       - Z2: should be an empty set
       - Z3: parameters that you will provide a sample.
       - Z4: parameters that you do not provide a sample.
         (optionally, you can choose sampling scheme and
          whether you want response surface for Z4).
       - G(Z1,Z3,Z4) is the simulator (opt_driver)

   (2) How to perform 2-level OUU? 
       In this case 
       - Z1: the optimization variables
       - Z2: the set of level-2 optimization parameters.
         If Z2 do not need to be published outside of the G
         function, then it can be specified as an empty set.
       - Z3: parameters that you will provide a sample for.
       - Z4: parameters that you do not provide a sample.
       - There are 2 options to how to set up G(Z1,Z2,Z3,Z4):
         (a) A user-provided level 2 optimizer that does

              G(Z1,Z2,Z3,Z4) = minimize_Z2{F(Z1,Z2,Z3,Z4)}

             where F(Z1,Z2,Z3,Z4) is embedded in G(Z1,...)

             In this case, the user will provide G(Z1,...)
             via opt_driver (i.e. opt_driver = gfunction)
         (b) A user-provided function F(Z1,...) such that

              G(Z1,Z2,Z3,Z4) = minimize_Z2 {F(Z1,Z2,Z3,Z4)}

             In this case, user is expected to provide the
             F(Z1,...) function via 'opt_driver = ffunction'
             and OUU provides the optimizer (BOBYQA).

   In case 1 and 2, Phi_{Z3,Z4} is a functional on G(Z1,...)
   with respect to Z3 and Z4, e.g. Phi_{Z3,Z4} may be:
   1. mean of G(Z1,Z2,Z3,Z4) with respect to Z3,Z4 (default)
   2. mean of G(Z1,Z2,Z3,Z4) + alpha * std dev of G(Z1,...)
   3. G(Z1,Z2,Z3*,Z4*) such that 
         Prob(G(Z1,Z2,Z3,Z4)>G(Z1,Z2,Z3*,Z4*)) = epsilon
   4. min_{Z3,Z4} G(Z1,Z2,Z3,Z4) given Z1,Z2 (robust opt.)
======================================================================
In the above formulation, the total no. of parameters M = 17
These parameters are to be divided into four groups:
(1) Stage 1 optimization parameters Z1 (M1 >= 1) 
(2) Stage 2 optimization (recourse) parameters Z2
(3) uncertain parameters Z3 (with a user-provided sample) 
(4) uncertain parameters Z4 
    - continuous parameters (PSUADE to generate sample), or
    - a large sample (created by PSUADE from RS) 
Thus, the first M1+M2 parameters are considered to be
optimization parameters, and M3+M4 are uncertain parameters
so that M = M1 + M2 + M3 + M4.
======================================================================
To reuse simulation results (e.g. from before abrupt
termination), turn on save_history and use_history
optimization options in the ANALYSIS section (e.g.
optimization save_history). You will see a text file
called 'psuade_ouu_history' afterward.
**********************************************************************
IF YOU ARE READY TO MOVE ON, ENTER 'y' AND RETURN : ======================================================================
*** OUUOptimizer detects nOutputs > 1.
    This will be interpreted to mean using cobyla to
*   solve inequality-constraint problems (G(x) < 0).
M1 = number of design (level 1 optim.) parameters
Enter M1 (between 1 and 17) : M2 = no. of recourse (level 2 optim.) parameters
Enter M2 (between 0 and 13) : M3 = number of discrete (scenario) parameters
Enter M3 (between 0 and 13) : In the following, please select type for each variable:
  1. design variable (level 1 optimization parameter)
  2. operating variable (level 2 optimization parameter)
  3. discrete uncertain variable (a sample will be given)
  4. continuous uncertain variable
NOTE: make sure your specification matches with above.
Type for variable 1 ? Type for variable 2 ? Type for variable 3 ? Type for variable 4 ? Type for variable 5 ? Type for variable 6 ? Type for variable 7 ? Type for variable 8 ? Type for variable 9 ? Type for variable 10 ? Type for variable 11 ? Type for variable 12 ? Type for variable 13 ? Type for variable 14 ? Type for variable 15 ? Type for variable 16 ? Type for variable 17 ? ======================================================================
Input    1 is a design parameter.
Input    2 is a continuous uncertain parameter.
Input    3 is a continuous uncertain parameter.
Input    4 is a continuous uncertain parameter.
Input    5 is a continuous uncertain parameter.
Input    6 is a continuous uncertain parameter.
Input    7 is a continuous uncertain parameter.
Input    8 is a continuous uncertain parameter.
Input    9 is a continuous uncertain parameter.
Input   10 is a design parameter.
Input   11 is a design parameter.
Input   12 is a design parameter.
Input   13 is a continuous uncertain parameter.
Input   14 is a continuous uncertain parameter.
Input   15 is a continuous uncertain parameter.
Input   16 is a continuous uncertain parameter.
Input   17 is a continuous uncertain parameter.
PDF type for Input     2 = Uniform
PDF type for Input     3 = Uniform
PDF type for Input     4 = Uniform
PDF type for Input     5 = Uniform
PDF type for Input     6 = Uniform
PDF type for Input     7 = Uniform
PDF type for Input     8 = Uniform
PDF type for Input     9 = Uniform
PDF type for Input    13 = Uniform
PDF type for Input    14 = Uniform
PDF type for Input    15 = Uniform
PDF type for Input    16 = Uniform
PDF type for Input    17 = Uniform
======================================================================
OUUOptimizer: setting optimization simulation driver.
              driver = C:\Users\fsoepyan\DOCUME~1\FOQUS_~1\FOQUSP~1.PY
======================================================================
Select which functional Phi_{Z3,Z4} to use: 
  1. mean of G(Z1,...) with respect to Z3,Z4 (default)
  2. mean of G(Z1,...) + beta * std dev of G(Z1,...)
  3. G(Z1,Z2,Z3*,Z4*) such that 
         Prob(G(Z1,...)>G(Z1,Z2,Z3*,Z4*)) = 1 - alpha
     This is also called value-at-risk with confidence
     level alpha.
Enter your choice of functional (1, 2 or 3) : Please select below the scheme to compute the returned
constraints from the ensemble constraints.
The returned constraints are computed from:
 1. the means of constraints from all sample runs
 2. the simulation with largest 2-norm violations
 3. the simulation with largest 1-norm violations
 4. the simulation with largest infinity-norm violation
NOTE: constraints are such that they should be >= 0.
Enter your choice (1 - 4) : OUUOptimizer: generating a sample for Z4. Two options:
(1) Users uploads a sample to PSUADE
(2) PSUADE can internally create a sample
Select option 1 or 2 : ERROR: input is not an integer.
Select option 1 or 2 : ======================================================================
A Z4 sample is needed from you. The file format should be:
line 1: <nSamples> <nInputs> 
line 2: <sample 1 input 1> <input 2> 
line 3: <sample 2 input 1> <input 2> 
...
Enter user sample file name : OUUOptimizer ERROR: user sample file 25 not found.

**Comment by sotorrio1** [comment]
@fsoepyan yeah, that's what I got. So basically I fixed the OUU handling constraints issue but now the psuade flow changed and we need to rewrite the script with the psuade commands. I'll keep you posted :)

**Comment by fsoepyan** [comment]
Thank you!

**Comment by fsoepyan** [comment]
- I downloaded FOQUS from PR #270
- I tested FOQUS using the example file with the 17 variables, the negCO2 objective, and the 3 inequality constraints
- I still got the same error that I got in my first comment
- The results do not appear in the OUU graph and OUU table

**Comment by sotorrio1** [comment]
@fsoepyan could you show me the psuadelog file? Thanks!

**Comment by fsoepyan** [comment]
Below is the psuade log file. Thank you!

**********************************************************************
*      Welcome to PSUADE (version 1.7.12)
**********************************************************************
PSUADE - A Problem Solving environment for 
         Uncertainty Analysis and Design Exploration (1.7.12)
(for help, enter <help>)
======================================================================
psuade> readOutput ERROR: nOutputs mismatch.
    check nOutputs in OUTPUT & PSUADE_IO sections.
PsuadeBase ERROR: cannot read file C:\Users\fsoepyan\DOCUME~1\FOQUS_~1\OUU_FI~1\OUUTEM~1.OUU or wrong format.
ERROR: run file not valid : check file format.
psuade> command y not recognized
psuade> command 4 not recognized
psuade> command 0 not recognized
psuade> command 0 not recognized
psuade> command 1 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 1 not recognized
psuade> command 1 not recognized
psuade> command 1 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 4 not recognized
psuade> command 1 not recognized
psuade> command 2 not recognized
psuade> command n not recognized
psuade> command 1 not recognized
psuade> command 20 not recognized
psuade> command y not recognized
psuade> command n not recognized
psuade> psuade terminates ...

**Comment by sotorrio1** [comment]
@fsoepyan could you clone my fork and try again? Thanks!

**Comment by fsoepyan** [comment]
Sorry, I ran FOQUS using the wrong version.

The psuade log file from the FOQUS version from PR #270 is in the attached Word file. Thank you!

[PSUADE_log_09_06_2018.docx](https://github.com/CCSI-Toolset/FOQUS/files/2358838/PSUADE_log_09_06_2018.docx)

**Comment by sotorrio1** [comment]
Do you get any error message?

**Comment by fsoepyan** [comment]
Yes, and it says:

OUU: Optimization error.
Please consult the FOQUS UQ developers for assistance.

**Comment by fsoepyan** [comment]
- PR #279 has been merged.
- I will close this issue.
